spring:
  application:
    name: GoodsApp  # 应用程序的名称，用于标识该 Spring Boot 应用。

  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: 123456
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/stf?useSSL=false&serverTimezone=UTC  # 数据库连接 URL，连接到本地的 MySQL 数据库 'dt'。
    username: root  # 数据库用户名。
    password: 1234  # 数据库密码。
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC 驱动类名，用于连接 MySQL 数据库。
  #文件上传
  servlet:
    multipart:
      max-file-size: 100MB # 文件最大上传大小，单位为字节，设置为 100MB。
      max-request-size: 1000MB # 请求的最大上传大小，单位为字节，设置为 1000MB。

  #redis数据持久化配置
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate 的 DDL 自动执行策略，可选值包括 'create'（每次启动时重新创建数据库结构）、'update'（更新数据库结构）、'validate'（验证数据库结构）、'none'（不自动执行任何操作）。
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true      # 是否显示 SQL 语句，设置为 true 可以在控制台中查看生成的 SQL。
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Hibernate 方言，指定使用的数据库类型，这里是 MySQL。

  data :
    redis:
      host: 127.0.0.1
      port: 6379
#      password: yourpassword
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8     # 最大活跃连接数
          max-idle: 8       # 最大空闲连接数
          min-idle: 0       # 最小空闲连接数
          max-wait: -1ms    # 获取连接的最大等待时间（-1 表示无限制）
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.128:8848

server:
  port: 9527  # 服务器端口，Spring Boot 应用将在这个端口上运行。

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 启用驼峰命名与下划线命名的自动转换。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # MyBatis 日志实现，配置为将日志输出到标准输出（控制台）。
  mapper-locations: SkyriseTechFronter-user/src/main/java/classpath:resources/com/tianchang/mapper/*.xml  # MyBatis 映射文件的位置，指定 XML 映射文件的路径。
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: SkyriseTechFronter-user/src/main/java/classpath:resources/com/tianchang/mapper/*.xml


#aliyun-oss
#aliyun:
#  oss:
#    endpoint: https://oss-cn-beijing.aliyuncs.com
#    bucketName: web-eg-example01
#    accessKeyId: LTAI5tNC3nPEEfGJ2P56wTvG
#    accessKeySecret: 5VeOsZIVmOSGPsBVWvIcyhE4y4MUbE

#事物管理配置
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.springframework.jdbc.core.JdbcTemplate: debug

